# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_reviewlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlist',
            name='fileInstance',
        ),
        migrations.AddField(
            model_name='reviewlist',
            name='fileInstance',
            field=models.ManyToManyField(to='analyze.File'),
        ),
    ]
