# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_auto_20180726_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlist',
            name='title',
            field=models.CharField(default='Review List', max_length=100),
        ),
    ]
