# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0006_auto_20180727_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='files',
        ),
        migrations.AddField(
            model_name='compare',
            name='file1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='compareFile1', to='analyze.File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compare',
            name='file2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='compareFile2', to='analyze.File'),
            preserve_default=False,
        ),
    ]
